### ISSUE TITLE
Suppress information about already downloaded trailers

### ISSUE THREAD

**Issue by forthrin** [aag/apple_trailer_downloader#10]
Please add an option so that only information the following information is printed:

- New trailers is printed
- Any kind of errors

This means suppressing the following information:

- Configuration information
- Already downloaded trailers

This will make it easier to glean what has happened since last time. It will also have the nice side effect that when running with `cron`, the user will only get an email when there are new trailers to check out.

**Comment by aag** [comment]
Hi forthrin,

I just pushed a commit that adds the `output_level` option. To have the script only print downloaded trailers, you can run the script with the command-line option `-o downloads` or put `output_level = downloads` in your config file.

Please give it a try and let me know if it's good enough for your needs.

**Comment by forthrin** [comment]
Seems to work like a charm! Maybe there should be only one line per movie to make it easier to read, but it's sort of nice to have both the URL and the filename, so...

**Comment by aag** [comment]
I went ahead and reduced the output to one line per file at the "downloads" output level. It now prints the movie name and type as well as the filename.

**Comment by forthrin** [comment]
Well, since the title and filename seem to be identical, I suggest simply:

    logging.info('Downloading ' + trailerUrl['type'] + ': ' + trailerFileName)

**Comment by aag** [comment]
> Well, since the title and filename seem to be identical, I suggest simply:

I went ahead and changed it to the format you suggested.
