### ISSUE TITLE
Feature Request: Download all trailers for a select few movies

### ISSUE THREAD

**Issue by forthrin** [aag/apple_trailer_downloader#17]
Add support for specifying a (short) list of movies where you want to download ALL trailers/clips, as opposed to most movies where you only want the main/first trailer.

To use for a select few movies with a high curiosity/anticipation where you immediately want every small nibble whenever something appears, eg. Star Wars, Top Gun, etc.

**Comment by aag** [comment]
Hey, thanks for the feature request. I think this sounds like a worthwhile addition, but I'm a little unsure how to implement it. How would you like to specify which movies get the full download treatment?

A few options that could work:
- Exact title
- Title substring
- Title regex
- Movie page URL

**Comment by forthrin** [comment]
Wouldn't the URLs that are printed on the screen while downloading (and added to the line-based file of downloaded trailers) be a natural choice?

**Comment by forthrin** [comment]
Any update on this? I'd really like to follow all trailers that are coming for the new Terminator movie, for example, rather having to constantly check for them or discover them by chance.

**Comment by aag** [comment]
Sorry it took so long, but I finally got around to implementing this feature. After downloading the newest version of the script, you will get all the Terminator: Dark Fate videos if you add this line to your `settings.cfg` file:

```
download_all_urls = https://trailers.apple.com/trailers/paramount/terminator-dark-fate/
```

If you have multiple movies you want all the videos for, you can list them with commas between them. For example:

```
download_all_urls = https://trailers.apple.com/trailers/paramount/terminator-dark-fate/,https://trailers.apple.com/trailers/lions_gate/knives-out/,https://trailers.apple.com/trailers/independent/monos/
```

**Comment by forthrin** [comment]
I'll be back.
