### ISSUE TITLE
Non-existing trailer makes script crash

### ISSUE THREAD

**Issue by forthrin** [aag/apple_trailer_downloader#19]
A trailer called `apple/the-banker` makes the script go 404 and cough up a call stack.

**Comment by aag** [comment]
Thanks for the bug report. I'm traveling at the moment without my computer, so I won't be able to get to it for a couple of days, but I'll take a look next week.

**Comment by aag** [comment]
It's a little hard to test, since the missing pages are no longer in the Just Added feed, but the script should now handle cases like this correctly. Please update to latest master or download v1.0.0-beta3 to get the fix.
