### ISSUE TITLE
Filename becomes 1080p though actual video size is 480p

### ISSUE THREAD

**Issue by forthrin** [aag/apple_trailer_downloader#4]
This is a cosmetic issue, but reporting it anyway. Example:

Checking for The Night Before
Could not find a trailer file URL with resolution '1080'. Retrying with '720'
Could not find a trailer file URL with resolution '720'. Retrying with the 'web' source
Could not find a trailer file URL with resolution '720'. Retrying with '480'
*** File already downloaded, skipping: The Night Before.Trailer.1080p.mov

**Comment by aag** [comment]
This is fixed in commit 5db4c1e.

**Comment by aag** [comment]
Note: after updating your script, it will re-download any trailers that were incorrectly named previous to this fix.
