### ISSUE TITLE
BeautifulSoup wants an explicit parser

### ISSUE THREAD

**Issue by forthrin** [aag/apple_trailer_downloader#5]
A minor problem, but Python complains about this every time the script is run. I'm on a Mac if that matters. Following the suggestion solves the problem. I guess the master code should fix this too?
 
    /usr/local/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
    
    To get rid of this warning, change this:
    
     BeautifulSoup([your markup])
    
    to this:
    
     BeautifulSoup([your markup], "html.parser")
    
      markup_type=markup_type))

**Comment by aag** [comment]
This is fixed in commit 79a9113.
