### ISSUE TITLE
Don't download trailer if local file exists

### ISSUE THREAD

**Issue by forthrin** [aag/apple_trailer_downloader#7]
With the current version, if a trailer does *not* exist in the download list, but *does* exist on the hard drive, it is still downloaded again, though this does not make any sense.

So if a local file exists with the same file size as on the server, simply skip downloading and add the filename to the download list.

(On a side note, if it's easy to make support for resuming incomplete downloads, it would be a nice thing, but this is really not so important, as downloading a trailer goes quite quickly with today's broadbands.)

**Comment by aag** [comment]
The newest version of the script now resumes the download of partial files and also skips fully downloaded files which are not in the download list.
